[package]
name = "clown-website-preview"
version = "0.1.0"
edition = "2024"
repository.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
image = { version = "^0.25.10", default-features = false, features = ["jpeg", "png"] }
bytes = "1.12"
thiserror = "2.0.20"
astral-tl = "0.8.0"
ureq = "3.4.1"

[dev-dependencies]
httpmock = {version="0.8.3", default-features=false}
tokio = "1.53.1"

[lints]
workspace = true
